/**
 * Accord Agent — Certificate Walrus Storage
 *
 * Archives generated PDF proof certificates to Walrus with 10-year retention.
 * Returns the blob ID to be embedded in the on-chain ProofCertificate object.
 */

import { storeBlob, getWalrusBlobUrl } from '../memory/walrus-memory.js';
import { logger } from '../utils/logger.js';

// 10-year retention: ~520 Sui epochs (assuming ~1 week per epoch).
// Reduced to 5 for testnet.
const CERT_EPOCHS = parseInt(process.env.WALRUS_CERT_EPOCHS ?? '5', 10);

export interface ProofMetadata {
  covenantId: string;
  milestoneIndex: number;
  clientAddress: string;
  contractorAddress: string;
  amountUsdsui: number;
  deliverableBlobId: string;
  issuedAt: number;
  transactionDigest?: string;
}

export interface StoredCertificate {
  blobId: string;
  viewUrl: string;
}

/**
 * Archives a PDF proof certificate buffer to Walrus.
 *
 * The blob is stored with 10-year (~520 epoch) retention — suitable for
 * legal-grade evidence of delivery and payment.
 *
 * @param pdfBuffer - Raw PDF bytes generated by the certificate generator.
 * @param metadata  - Metadata describing the proof (used for logging/audit trail).
 * @returns blobId and a direct view URL for the Walrus aggregator.
 */
export async function archiveProofCertificate(
  pdfBuffer: Buffer,
  metadata: ProofMetadata,
): Promise<StoredCertificate> {
  logger.info(
    `Archiving proof certificate: covenant=${metadata.covenantId} milestone=${metadata.milestoneIndex} size=${pdfBuffer.length}b`,
  );

  const blobId = await storeBlob(pdfBuffer, CERT_EPOCHS);
  const viewUrl = getWalrusBlobUrl(blobId);

  logger.info(
    `Certificate archived: blobId="${blobId}" covenant=${metadata.covenantId} milestone=${metadata.milestoneIndex}`,
  );

  return { blobId, viewUrl };
}
