/// Accord — Proof Certificate Module
///
/// Mints an immutable, non-transferable on-chain `ProofCertificate` for every
/// released milestone. The certificate embeds:
///   1. The Walrus blob ID of the contractor's deliverable.
///   2. The Walrus blob ID of the generated PDF proof artifact.
///
/// Security:
///   - `mint_proof_certificate` requires `&ArcaCap` from `accord::covenant`.
///   - `ProofCertificate` has only `key` ability — cannot be wrapped, stored in
///     collections, or transferred after the initial `transfer::transfer` call.
///   - This makes the certificate effectively soulbound to the contractor's address.
module accord::proof {
    use sui::object::{Self, ID, UID};
    use sui::transfer;
    use sui::tx_context::{Self, TxContext};
    use sui::event;
    use accord::covenant::ArcaCap;

    // ─── Event ──────────────────────────────────────────────────────────────────

    /// Emitted when a ProofCertificate is minted for a milestone release.
    public struct CertificateMinted has copy, drop {
        certificate_id: ID,
        covenant_id: ID,
        milestone_index: u64,
        contractor: address,
        amount_usdsui: u64,
        walrus_blob_id: vector<u8>,
    }

    // ─── Core Struct ──────────────────────────────────────────────────────────

    /// Non-transferable proof of milestone completion.
    /// Minted once per released milestone, owned by the contractor.
    /// The `walrus_blob_id` links to the deliverable stored on Walrus.
    /// The `walrus_cert_blob_id` links to the PDF certificate stored on Walrus.
    ///
    /// This object is the on-chain anchor for legal-grade evidence of:
    ///   - What was agreed (covenant_id → covenant on-chain)
    ///   - What was delivered (walrus_blob_id → immutable Walrus blob)
    ///   - When and how much was paid (amount_usdsui + issued_at_epoch)
    public struct ProofCertificate has key {
        id: UID,
        /// The covenant this certificate belongs to.
        covenant_id: ID,
        /// Which milestone (0-indexed) this certificate covers.
        milestone_index: u64,
        /// Client's Sui address.
        client: address,
        /// Contractor's Sui address (also the owner of this object).
        contractor: address,
        /// Amount paid in USDSUI base units (6 decimals).
        amount_usdsui: u64,
        /// Walrus blob ID of the delivered work artifact.
        walrus_blob_id: vector<u8>,
        /// Walrus blob ID of the PDF proof certificate generated by Arca.
        walrus_cert_blob_id: vector<u8>,
        /// Sui epoch at which this certificate was issued.
        issued_at_epoch: u64,
    }

    // ─── Public Functions ─────────────────────────────────────────────────────

    /// Mints a `ProofCertificate` and transfers it to the contractor's address.
    ///
    /// Called exclusively by the Arca agent as part of the milestone release PTB.
    /// Requires `&ArcaCap` — the sole capability gating autonomous operations.
    ///
    /// The certificate is non-transferable after minting (only `key` ability).
    public fun mint_proof_certificate(
        _cap: &ArcaCap,
        covenant_id: ID,
        milestone_index: u64,
        client: address,
        contractor: address,
        amount_usdsui: u64,
        walrus_blob_id: vector<u8>,
        walrus_cert_blob_id: vector<u8>,
        ctx: &mut TxContext,
    ) {
        let id = object::new(ctx);
        let cert_id = object::uid_to_inner(&id);
        let cert = ProofCertificate {
            id,
            covenant_id,
            milestone_index,
            client,
            contractor,
            amount_usdsui,
            walrus_blob_id,
            walrus_cert_blob_id,
            issued_at_epoch: tx_context::epoch(ctx),
        };

        event::emit(CertificateMinted {
            certificate_id: cert_id,
            covenant_id,
            milestone_index,
            contractor,
            amount_usdsui,
            walrus_blob_id,
        });

        transfer::transfer(cert, contractor);
    }

    // ─── Read-Only Accessors ──────────────────────────────────────────────────

    public fun cert_covenant_id(c: &ProofCertificate): ID { c.covenant_id }
    public fun cert_milestone_index(c: &ProofCertificate): u64 { c.milestone_index }
    public fun cert_client(c: &ProofCertificate): address { c.client }
    public fun cert_contractor(c: &ProofCertificate): address { c.contractor }
    public fun cert_amount(c: &ProofCertificate): u64 { c.amount_usdsui }
    public fun cert_blob_id(c: &ProofCertificate): &vector<u8> { &c.walrus_blob_id }
    public fun cert_cert_blob_id(c: &ProofCertificate): &vector<u8> { &c.walrus_cert_blob_id }
    public fun cert_issued_at(c: &ProofCertificate): u64 { c.issued_at_epoch }
}
